<h2>My Account</h2>
<?php if($this->identity == null) { ?>
	<p>To log in <a href="/user/login">click here</a></p>
	<?php 
// 	if (isset($this->needsReset)) 
// 	{
// 	}		 
	?>
<?php }else{ ?>
	<p>Welcome back <?php echo $this->identity->first_name; 		echo $this->needsReset;	?></p>
	<p>To download the member directory, <a href="/docs/directorypdf">Click Here</a></p>
	<p>To log out <a href="/user/logout">click here</a></p>
<?php } ?>