<tr>
	<td class="links">
		<a href="/user/update/user_id/<?php echo $this->user_id; ?>">Update</a>
		<a href="/user/delete/user_id/<?php echo $this->user_id; ?>">Delete</a>
	</td>
	<td><?php echo $this->username ?></td>
	<td><?php echo $this->email ?></td>
	<td><?php echo $this->last_name ?></td>
	<td><?php echo $this->first_name ?></td>	
	<td><?php echo $this->role ?></td>
	<td><?php echo ($this->reset_password==TRUE?'yes':'no') ?>
</tr>